import React, { useState } from 'react'
import CardLaptop from '../laptoppage/CardLaptop'

function CardsLaptop() {
   
    const shipss = [
        {
            id: 1,
            imgurl: "img/laptop/5.webp",
            fast: "flex",
            free: "none",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"none",
            down: "block",
            cardleft:"none",
            cardright:"none",
            textp:"HP",
            textspan:"Victus 16-r0035nt Intel I5-13500h Ddr5 16gb 1tb Ssd Gen4",
            money:"32.999 TL",
            del:"34.999 TL",
            color:"#bb0000",
            star:"block"
        },
        {
            id: 2,
            imgurl: "img/laptop/6.webp",
            fast: "flex",
            free: "none",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"none",
            down: "none",
            cardleft:"none",
            cardright:"none",
            textp:"Asus",
            textspan:"Rog Flow Z13 Gz301vf-mu019 I9 13900h 16gb 512 Gb Ssd Rtx",
            money:"37.989 TL",
            color:"#f27a1a",
            star:"none"
        },
        {
            id: 3,
            imgurl: "img/laptop/7.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/yildizli.webp",
            imgleftdisplay:"none",
            down: "block",
            cardleft:"none",
            cardright:"none",
            textp:"Lenovo",
            textspan:"Legion 5 82rb00dctx Intel Core I7-12700h 16gb 512gb Ssd",
            money:"42.272 TL",
            del:"42.499 TL",
            color:"#bb0000"
        },
        {
            id: 4,
            imgurl: "img/laptop/8.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"none",
            down: "none",
            cardleft:"none",
            cardright:"none",
            textp:"Lenovo",
            textspan:"Ideapad 3 15alc6 Amd Ryzen 5 5500u 8gb/256gb Ssd",
            money:"10.531 TL",
            color:"#f27a1a"
        },
        {
            id: 5,
            imgurl: "img/laptop/9.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"none",
            down: "none",
            cardleft:"none",
            cardright:"none",
            textp:"MSI",
            textspan:"MODERN 15 B7M-078XTR R5-7530U DDR4 UMA 512GB SSD",
            color:"#f27a1a",
            money:"15.299 TL",
        },
        {
            id: 6,
            imgurl: "img/laptop/10.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"none",
            down: "none",
            cardleft:"none",
            cardright:"none",
            textp:"ASUS",
            textspan:"D515da-br408 12 Gb Ram Ryzen 3 3250u 256 Gb Ssd 15.6",
            color:"#f27a1a",
            money:"8.999 TL",
            // del:"12.599 TL",
        },
        {
            id: 7,
            imgurl: "img/laptop/11.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"none",
            down: "block",
            cardleft:"none",
            cardright:"none",
            textp:"LENOVO",
            textspan:"Ideapad1/Celeron N4120/4GB emmc",
            color:"#bb0000",
            money:"5.285 TL",
            del:"5.650 TL",
            star:"none",
        },
        {
            id: 8,
            imgurl: "img/laptop/12.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/yildizli.webp",
            imgleftdisplay:"none",
            down: "block",
            cardleft:"none",
            cardright:"none",
            textp:"HP",
            textspan:"Victus Gaming Laptop I5 12500h 16gb 1tb Ssd Rtx3050ti Dos 15.6",
            color:"#bb0000",
            money:"20.299 TL",
            star:"none"
        },
        {
            id: 9,
            imgurl: "img/laptop/13.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"block",
            down: "block",
            cardleft:"block",
            cardright:"block",
            textp:"HP",
            textspan:"Victus Gaming Laptop I5 12500h 16gb 1tb Ssd Rtx3050ti Dos 15.6",
            color:"#bb0000",
            money:"20.299 TL",
        },
        {
            id: 10,
            imgurl: "img/laptop/14.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"block",
            down: "none",
            cardleft:"none",
            cardright:"none",
            textp:"HP",
            textspan:"Victus Gaming Laptop I5 12500h 16gb 1tb Ssd Rtx3050ti Dos 15.6",
            color:"#f27a1a",
            money:"20.299 TL",
        },
        {
            id: 11,
            imgurl: "img/laptop/15.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"block",
            down: "block",
            cardleft:"none",
            cardright:"none",
            textp:"Excalibur",
            textspan:"Excalibur G870.1245-BVAOX-B Intel Core i5-12450H 16BG RAM",
            color:"#f27a1a",
            money:"22.499 TL",
        },
        {
            id: 12,
            imgurl: "img/laptop/16.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/ildizli.webp",
            imgleftdisplay:"block",
            down: "none",
            cardleft:"none",
            cardright:"none",
            textp:"Monster",
            textspan:"Tulpar T7 V20.5.6 Intel Core I7-12700h 32 Gb Ram 1tb Ss",
            color:"#f27a1a",
            money:"34.999 TL",
        },
        {
            id: 13,
            imgurl: "img/laptop/17.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"none",
            down: "block",
            cardleft:"block",
            cardright:"none",
            textp:"Acer",
            textspan:"Nitro 5 Intel Core i7-12700H 16GB 512GB SSD 4GB RTX3050Ti",
            color:"#bb0000",
            money:"20.999 TL",
        },
        {
            id: 14,
            imgurl: "img/laptop/18.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"block",
            down: "none",
            cardleft:"none",
            cardright:"none",
            textp:"Acer",
            textspan:"Nitro 5 Intel Core i7-12700H 16GB 512GB SSD 4GB RTX3050Ti",
            color:"#f27a1a",
            money:"19.998 TL",
        },
        {
            id: 15,
            imgurl: "img/laptop/19.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"block",
            down: "none",
            cardleft:"none",
            cardright:"none",
            textp:"Acer",
            textspan:"Nitro 5 Intel Core i7-12700H 16GB 512GB SSD 4GB RTX3050Ti",
            color:"#f27a1a",
            money:"21.856TL",
        },
        {
            id: 16,
            imgurl: "img/laptop/20.webp",
            fast: "flex",
            free: "flex",
            imgleft: "img/veryshipping/en-çok-satan.webp",
            imgleftdisplay:"block",
            down: "none",
            cardleft:"none",
            cardright:"none",
            textp:"Acer",
            textspan:"Nitro 5 Intel Core i7-12700H 16GB 512GB SSD 4GB RTX3050Ti",
            color:"#f27a1a",
            money:"17.500 TL",
        },
    ]
    const [cards,setCards] = useState(shipss)
  return (
    <>
    <div key={cards.id} className="row">
        <CardLaptop cards={cards}/>
    </div>
    
    </>
  )
}

export default CardsLaptop